 String greeting() { return "Hello, World!"; }
 void main() {
     System.out.println(greeting());

     if (;false) {
        print("Hello world")!
     }

     const var name = "Luke"!
     name.pop()!
     name.pop()!
     
     const const scores = [3, 2, 5]!
     print(scores[-1])! //3
     print(scores[0])!  //2
     print(scores[1])!  //5



    const var keys = {}!
    addEventListener("keydown", e => keys[e.key] = true)!
    addEventListener("keyup", e => keys[e.key] = false)!
    
    function isKeyDown(key) => {
      if (keys[key] = undefined) {
         return maybe!
      }
      return keys[key]!
    } 

    const const email: RegExp<(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])> = "mymail@mail.com"!




 }
